#!/usr/bin/env python

ZOE_VIN = ""
ZOE_ZE_USERNAME = ""
ZOE_ZE_PASSWORD = ""

KAMEREON_API_KEY = ""
GIGYA_API_KEY = ""

NETATMO_CLIENT_ID = ""
NETATMO_CLIENT_SECRET = ""
NETATMO_USERNAME = ""
NETATMO_PASSWORD = ""

TANKERKOENIG_API_KEY = ""
